name: gwaihir
channels:
  - defaults
  - anaconda
  - menpo
  - conda-forge
dependencies:
  - python
  - asteval
  - autopep8
  - bcdi
  - black
  - cryptography
  - doit
  - fabio
  - h5py
  - hdf5plugin
  - imageio
  - ipyfilechooser
  - ipython
  - ipyvolume
  - ipywidgets
  - jupyter
  - jupyterlab
  - lmfit
  - matplotlib
  - h5py
  - moviepy
  - notebook
  - numexpr
  - numpy
  - pandas
  - pytables
  - pynx
  - Pillow
  - pyaml
  - PyQt5
  - pyyaml
  - scikit
  - scipy
  - silx
  - tables
  - tqdm
  - traitlets
  - traits
  - vtk
  - xrayutilities
  - pycodestyle
  - pydocstyle
  - pip:
    - hdf5plugin
