scans: 324
root_folder: "/data/id01/inhouse/david/PETRA_December_2021/2021_P10/raw/"
save_dir: "/data/id01/inhouse/david/PETRA_December_2021/Ar_RT/G3/align_03324/preprocessing/"
data_dir: "/data/id01/inhouse/david/PETRA_December_2021/2021_P10/raw/"
sample_name: "align_03"
comment: ""
debug: False
flag_interact: True
background_plot: "0.5"
centering_method: "max"
fix_bragg: None
fix_size: None
center_fft: "crop_sym_ZYX"
pad_size: None
mask_zero_event: False
median_filter: "skip"
median_filter_order: 7
reload_previous: False
reload_orthogonal: False
preprocessing_binning: [1, 2, 2]
save_rawdata: False
save_to_npz: True
save_to_mat: False
save_to_vti: False
save_as_int: False
beamline: "P10"
actuators: None
is_series: False
rocking_angle: "outofplane"
specfile_name: None
custom_scan: False
custom_images: None
custom_monitor: None
detector: "Eiger4M"
phasing_binning: [1, 1, 1]
linearity_func: None
roi_detector: [676, 1076, 1140, 1540]
normalize_flux: "skip"
photon_threshold: 0
photon_filter: "loading"
bin_during_loading: True
frames_pattern: None
background_file: None
hotpixels_file: None
flatfield_file: None
template_imagefile: "_master.h5"
use_rawdata: True
interpolation_method: "linearization"
fill_value_mask: 0
beam_direction: [1, 0, 0]
sample_offsets: [0, 0, 0, 0]
sdd: 1.83
energy: 11294
custom_motors: None
align_q: True
ref_axis_q: "y"
outofplane_angle: 28.719559085822546
inplane_angle: -0.6833226163240554
tilt_angle: 0.003
sample_inplane: [1, 0, 0]
sample_outofplane: [0, 0, 1]
offset_inplane: 0.0
cch1: 1340
cch2: 1050
detrot: 0.0
tiltazimuth: 360.0
tilt_detector: 0.0
backend: "Qt5Agg"
